// src/agents/codex/config.ts

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import * as os from 'node:os';

/** Write a Compresso Codex configuration file (~/.codex/config.toml). */
export async function writeCodexConfig(opts: {
  port: number;
  apiKey?: string;
  model?: string;
}): Promise<void> {
  const home = os.homedir();
  const dir = path.join(home, '.codex');
  await fs.mkdir(dir, { recursive: true });
  const file = path.join(dir, 'config.toml');
  const lines: string[] = [
    '# Generated by compresso codex --setup',
    `[provider]`,
    `base_url = "http://127.0.0.1:${opts.port}"`,
  ];
  if (opts.model) lines.push(`model = "${opts.model}"`);
  if (opts.apiKey) lines.push(`api_key = "${opts.apiKey}"`);
  await fs.writeFile(file, lines.join('\n') + '\n', 'utf8');
}
